### ISSUE TITLE
Match restart when there are errors in Lua script

### ISSUE THREAD

**Issue by PawelWojciechowski** [vincentvanbush/evaLUAtion2#6]
There is a problem with evaLUAtion2 when a lua script contains some errors. 
When we start correct the script and then add error(s) (like if without then), the evaLUAtion2 is run with the old scripts and we cannot see the error. They are visible when the whole application is restarted. Probably, the same is when there is an error in script and we correct it. It would (probably) requires restart too.

**Comment by vincentvanbush** [comment]
We've probably found the reason behind this bug and are on course to fix it, stay tuned.

**Comment by vincentvanbush** [comment]
[https://github.com/vincentvanbush/evaLUAtion2/commit/26b07280d53c446b4962faa76ca39c60488a30f5](Fixed)
